### ISSUE TITLE
Some English titles are also listed in synonyms

### ISSUE THREAD

**Issue by reconman** [Soitora/TMDB-PAS-Assistant#1]
Some TMDB entries have alternative titles where the original English title is included.

For example, `Thus Spoke Kishibe Rohan`: https://www.themoviedb.org/tv/118443/titles?language=en-US

That's probably an error in the database so I'm planning on deleting the duplicate title.

I think the best way would be to add `mediaName` as a parameter to `getFormattedTitles()` and then filter out any alternative titles equal to `mediaName`.

**Comment by Soitora** [comment]
Yeah I removed this manually when I did my conversion, I don't know how I didn't even give it a thought to clean them out at the get-go

I'll check it out in a bit

**Comment by Soitora** [comment]
Hopefully e9a3847d0c59ccaea45f68045a1701c3211506d6 fixed it

## 1.0.0
```yml
- title: "Thus Spoke Kishibe Rohan"
  # https://www.themoviedb.org/tv/118443
  # https://www.thetvdb.com/dereferrer/series/391636
  # https://www.imdb.com/title/tt13887556/
  synonyms:
    - "Kishibe Rohan wa Ugokanai"
    - "Thus Spoke Kishibe Rohan"
    - "Thus Spoke Rohan Kishibe"
  seasons:
    - season: 1
      anilist-id: 0
```

## 1.0.1
```yml
- title: "Thus Spoke Kishibe Rohan"
  # https://www.themoviedb.org/tv/118443
  # https://www.thetvdb.com/dereferrer/series/391636
  # https://www.imdb.com/title/tt13887556/
  synonyms:
    - "Kishibe Rohan wa Ugokanai"
    - "Thus Spoke Rohan Kishibe"
  seasons:
    - season: 1
      anilist-id: 0
```
